### ISSUE TITLE
unable to build mysql on a vapor project

### ISSUE THREAD

**Issue by kaka21garuda** [vapor/mysql#67] opened 2016-11-26 23:15 UTC
when I run `vapor build --mysql`

> /Users/bukacakrawala/Desktop/PersonalProject/bukacakVapor/bukacakV/Packages/CMySQL-1.0.0/module.modulemap:14:12: error: header '/usr/local/include/mysql/mysql.h' not found
    header "/usr/local/include/mysql/mysql.h"

> /Users/bukacakrawala/Desktop/PersonalProject/bukacakVapor/bukacakV/Packages/MySQL-1.0.2/Sources/MySQL/Bind+Node.swift:8:12: error: could not build Objective-C module 'CMySQLMac'
    import CMySQLMac

This is the package that I installed in my project: `.Package(url: "https://github.com/vapor/mysql-provider.git", majorVersion: 1, minor: 0)`.

**Comment by BrettRToomey** [comment] 2016-11-26 23:28
Did you install MySQL with brew? If not, you're going to have to install it or make a symbolic link with your current instal to point to the locations the compiler is expecting.

**Comment by kaka21garuda** [comment] 2016-11-27 04:50
@BrettRToomey yes I did install MySQL with brew, running a local MySQL server on my machine, but when I try to link them up. I always got those errors

**Comment by tannernelson** [comment] 2016-12-02 18:29
Duplicate of https://github.com/vapor/mysql/issues/29

**Closed by tannernelson** 2016-12-02 18:29 UTC
